dfx canister call backend_rust clear_face_detection_model_bytes
dfx canister call backend_rust clear_face_recognition_model_bytes
ic-file-uploader backend_rust append_face_detection_model_bytes version-RFB-320.onnx
ic-file-uploader backend_rust append_face_recognition_model_bytes face-recognition.onnx
dfx canister call backend_rust setup_models